---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "Project for OpenShift Advanced Cluster Management operator and MultiClusterHub"
    openshift.io/display-name: "Advanced Cluster Management"
  name: open-cluster-management

















