kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: open-cluster-management

#commonAnnotations:
#  argocd.argoproj.io/sync-wave: "0"

resources:
  - acm-operator-namespace.yml
  - acm-operator-subscription.yml
  - acm-operator-operatorgroup.yml
  - acm-operator-mch.yml