kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: santa-message

bases:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: santa-message
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1