apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSet
metadata:
  name: 1262-glenrose
spec:
  clusterSelector:
    selectorType: LegacyClusterSetLabel
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: 1262-glenrose-placement
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: cluster.open-cluster-management.io/clusterset, operator: In, values: ["1262-glenrose"]}
