kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-file-integrity

bases:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: file-integrity-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: '4.7'