kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: rhacs-operator

#commonAnnotations:
#  argocd.argoproj.io/sync-wave: "0"

resources:
  - rhacs-operator-namespace.yml
  - rhacs-operator-subscription.yml
  - rhacs-operator-operatorgroup.yml