kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-nfd

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: nfd
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'