kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: nvidia-gpu-operator

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: gpu-operator-certified
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'