apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-stores
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: clusterType, operator: In, values: ["store"]}
