apiVersion: app.k8s.io/v1beta1
kind: Application      
metadata:
  annotations:  
    apps.open-cluster-management.io/deployables: ""
    apps.open-cluster-management.io/subscriptions: applications/platform-subscription-1
    apps.open-cluster-management.io/reconcile-rate: high
  creationTimestamp: "2022-12-02T00:01:12Z" 
  generation: 1 
  name: platform      
  namespace: platform-applications
spec:    
  componentKinds:      
  - group: apps.open-cluster-management.io  
    kind: Subscription 
  descriptor: {}
  selector:     
    matchExpressions:  
    - key: app  
      operator: In     
      values:   
      - platform
---
apiVersion: apps.open-cluster-management.io/v1     
kind: Subscription     
metadata:
  annotations:  
    apps.open-cluster-management.io/cluster-admin: "true" 
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/reconcile-rate: high
    apps.open-cluster-management.io/git-path: manifests/acm/applications
    apps.open-cluster-management.io/reconcile-option: replace      
  labels:
    app: platform     
    app.kubernetes.io/part-of: platform
  name: platform-subscription-1
  namespace: platform-applications     
spec:    
  channel: ggithubcom-richmitch-ocp-cluster-management-ns/ggithubcom-richmitch-ocp-cluster-management      
  placement:    
    placementRef:      
      kind: PlacementRule     
      name: platform-placement-1 
---
apiVersion: apps.open-cluster-management.io/v1 
kind: Channel      
metadata:   
  annotations:     
    apps.open-cluster-management.io/reconcile-rate: high
#    apps.open-cluster-management.io/webhook-enabled: "true"
  name: gonsultingredhatcom-woolworths-group-stores-openshift-poc
  namespace: gonsultingredhatcom-woolworths-group-stores-openshift-poc-ns
spec:
  pathname: https://gitlab.consulting.redhat.com/woolworths-group/stores-openshift-poc
  secretRef:
    name: gonsultingredhatcom-woolworths-group-stores-openshift-poc-auth
  type: Git
---
apiVersion: apps.open-cluster-management.io/v1     
kind: PlacementRule    
metadata:
  labels:
    app: platform     
  name: platform-placement-1 
  namespace: platform-applications     
spec:    
  clusterSelector:     
    matchLabels:
      local-cluster: "true"