kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: camera-check

resources:
  - ../../base

#patches:
#  - target:
#      kind: CronJob
#      name: camera-check
#    patch: |-
#      - op: replace
#        path: /spec/jobTemplate/spec/template/spec/containers/.../name=IP
#        value: "10.47.208.92"