apiVersion: v2
name: cluster
description: Day 2 configuration of a cluster
type: application
version: 0.0.1
maintainers:
  - name: richmitch
dependencies:
- name: nfd
  version: 0.3.0
  repository: https://richmitch.github.io/ocp-cluster-management/charts/
- name: nmstate
  version: 0.1.1
  repository: https://richmitch.github.io/ocp-cluster-management/charts/
- name: gitops
  version: 0.1.0
  repository: https://richmitch.github.io/ocp-cluster-management/charts/
- name: compliance
  version: 0.1.1
  repository: https://richmitch.github.io/ocp-cluster-management/charts/
