kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-operators

#commonAnnotations:
#  argocd.argoproj.io/sync-wave: "0"

resources:
  - nmstate-operator-namespace.yml
  - nmstate-operator-subscription.yml
  - nmstate-operator-operatorgroup.yml
  - nmstate-operator-nmstate.yml