kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: nvidia-gpu-operator

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: dcgmproftester
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 16