apiVersion: app.k8s.io/v1beta1 
kind: Application   
metadata:
  annotations:  
    apps.open-cluster-management.io/deployables: ""  
  name: governance-policies
  namespace: applications  
spec:
  componentKinds:   
  - group: apps.open-cluster-management.io
    kind: Subscription     
  selector:     
    matchExpressions:      
    - key: app  
      operator: In  
      values:   
      - governance-policies 
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription  
metadata:
 annotations: 
   apps.open-cluster-management.io/cluster-admin: "true" 
   apps.open-cluster-management.io/git-branch: main      
   apps.open-cluster-management.io/git-path: manifests/policies/overlays/hub
   apps.open-cluster-management.io/reconcile-option: replace
 labels:
   app: governance-policies
   app.kubernetes.io/part-of: governance-policies
   apps.open-cluster-management.io/reconcile-rate: medium
 name: governance-policies-subscription-1     
 namespace: applications
spec:    
 channel: ggithubcom-richmitch-ocp-cluster-management-ns/ggithubcom-richmitch-ocp-cluster-management 
 placement:   
   placementRef:     
     kind: PlacementRule
     name: governance-policies-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule   
metadata:     
 labels:     
   app: governance-policies
 name: governance-policies-placement-1
 namespace: applications     
spec:
 clusterSelector:    
   matchLabels:      
     local-cluster: "true"
