apiVersion: app.k8s.io/v1beta1 
kind: Application   
metadata:     
  name: rh-pipelines-operator
  namespace: applications  
spec:
  componentKinds:   
  - group: apps.open-cluster-management.io
    kind: Subscription     
  selector:     
    matchExpressions:      
    - key: app  
      operator: In  
      values:   
      - rh-pipelines-operator 
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription  
metadata:
 annotations: 
   apps.open-cluster-management.io/cluster-admin: "true" 
   apps.open-cluster-management.io/git-branch: main
   apps.open-cluster-management.io/reconcile-rate: medium
   apps.open-cluster-management.io/git-path: manifests/operators/pipelines/overlays/latest
   apps.open-cluster-management.io/reconcile-option: replace
 labels:
   app: rh-pipelines-operator
   app.kubernetes.io/part-of: rh-pipelines-operator    
 name: rh-pipelines-operator-subscription-1     
 namespace: applications
spec:    
 channel: ggithubcom-richmitch-ocp-cluster-management-ns/ggithubcom-richmitch-ocp-cluster-management 
 placement:   
   placementRef:     
     kind: PlacementRule
     name: rh-pipelines-operator-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule   
metadata:     
 labels:     
   app: rh-pipelines-operator  
 name: rh-pipelines-operator-placement-1
 namespace: applications     
spec:
 clusterSelector:    
   matchLabels:      
     vendor: OpenShift

