apiVersion: app.k8s.io/v1beta1 
kind: Application   
metadata:
  annotations:  
    apps.open-cluster-management.io/deployables: ""  
#    apps.open-cluster-management.io/subscriptions: applications/santa-message-subscription-1,applications/santa-message-subscription-1-local
    open-cluster-management.io/user-group: c3lzdGVtOnNlcnZpY2VhY2NvdW50cyxzeXN0ZW06c2VydmljZWFjY291bnRzOm9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50LHN5c3RlbTphdXRoZW50aWNhdGVk
    open-cluster-management.io/user-identity: c3lzdGVtOnNlcnZpY2VhY2NvdW50Om9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50Om11bHRpY2x1c3Rlci1hcHBsaWNhdGlvbnM=      
  name: santa-message
  namespace: applications  
spec:
  componentKinds:   
  - group: apps.open-cluster-management.io
    kind: Subscription     
  selector:     
    matchExpressions:      
    - key: app  
      operator: In  
      values:   
      - santa-message 
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription  
metadata:
 annotations: 
   apps.open-cluster-management.io/cluster-admin: "true" 
   apps.open-cluster-management.io/reconcile-rate: high
   apps.open-cluster-management.io/git-branch: main      
   apps.open-cluster-management.io/git-path: manifests/applications/santa-message/overlays/replicas-1
   apps.open-cluster-management.io/reconcile-option: replace
   open-cluster-management.io/user-group: c3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgsc3lzdGVtOmF1dGhlbnRpY2F0ZWQ=   
   open-cluster-management.io/user-identity: cmljaGFyZA==
 labels:
   app: santa-message
   app.kubernetes.io/part-of: santa-message
 name: santa-message-subscription-1     
 namespace: applications
spec:    
 channel: gonsultingredhatcom-woolworths-group-stores-openshift-poc-ns/gonsultingredhatcom-woolworths-group-stores-openshift-poc 
 placement:   
   placementRef:     
     kind: PlacementRule
#     name: app-placement-none
#     name: app-placement-staging
     name: app-placement-1339-top-ryde
#     name: app-placement-all-stores

