apiVersion: app.k8s.io/v1beta1 
kind: Application   
metadata:
  annotations:  
    apps.open-cluster-management.io/deployables: ""  
#    apps.open-cluster-management.io/subscriptions: applications/stable-diffusion-subscription-1,applications/stable-diffusion-subscription-1-local
    open-cluster-management.io/user-group: c3lzdGVtOnNlcnZpY2VhY2NvdW50cyxzeXN0ZW06c2VydmljZWFjY291bnRzOm9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50LHN5c3RlbTphdXRoZW50aWNhdGVk
    open-cluster-management.io/user-identity: c3lzdGVtOnNlcnZpY2VhY2NvdW50Om9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50Om11bHRpY2x1c3Rlci1hcHBsaWNhdGlvbnM=      
  name: stable-diffusion
  namespace: applications  
spec:
  componentKinds:   
  - group: apps.open-cluster-management.io
    kind: Subscription     
  selector:     
    matchExpressions:      
    - key: app  
      operator: In  
      values:   
      - stable-diffusion 
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription  
metadata:
 annotations: 
   apps.open-cluster-management.io/cluster-admin: "true" 
   apps.open-cluster-management.io/git-branch: main
   apps.open-cluster-management.io/reconcile-rate: high
   apps.open-cluster-management.io/git-path: manifests/applications/stable-diffusion/create-app
   apps.open-cluster-management.io/reconcile-option: replace
   open-cluster-management.io/user-group: c3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgsc3lzdGVtOmF1dGhlbnRpY2F0ZWQ=   
   open-cluster-management.io/user-identity: cmljaGFyZA==
 labels:
   app: stable-diffusion
   app.kubernetes.io/part-of: stable-diffusion
 name: stable-diffusion-app-subscription-1     
 namespace: applications
spec:    
 channel: ggithubcom-richmitch-ocp-cluster-management-ns/ggithubcom-richmitch-ocp-cluster-management 
 placement:   
   placementRef:     
     kind: PlacementRule
     name: app-placement-1339-top-ryde
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription  
metadata:
 annotations: 
   apps.open-cluster-management.io/cluster-admin: "true" 
   apps.open-cluster-management.io/git-branch: main      
   apps.open-cluster-management.io/git-path: manifests/applications/stable-diffusion/create-data
   apps.open-cluster-management.io/reconcile-option: replace
   open-cluster-management.io/user-group: c3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgsc3lzdGVtOmF1dGhlbnRpY2F0ZWQ=   
   open-cluster-management.io/user-identity: cmljaGFyZA==
 labels:
   app: stable-diffusion
   app.kubernetes.io/part-of: stable-diffusion
   apps.open-cluster-management.io/reconcile-rate: medium
 name: stable-diffusion-data-subscription-1     
 namespace: applications
spec:    
 channel: ggithubcom-richmitch-ocp-cluster-management-ns/ggithubcom-richmitch-ocp-cluster-management 
 placement:   
   placementRef:     
     kind: PlacementRule
     name: app-placement-1339-top-ryde
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule   
metadata:     
 annotations:
   open-cluster-management.io/user-group: c3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgsc3lzdGVtOmF1dGhlbnRpY2F0ZWQ=
   open-cluster-management.io/user-identity: cmljaGFyZA==
 labels:     
   app: stable-diffusion  
 name: app-placement-1339-top-ryde
 namespace: applications     
spec:
 clusterSelector:    
   matchLabels:      
     cluster.open-cluster-management.io/clusterset: 1339-top-ryde
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule   
metadata:     
 annotations:
   open-cluster-management.io/user-group: c3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgsc3lzdGVtOmF1dGhlbnRpY2F0ZWQ=
   open-cluster-management.io/user-identity: cmljaGFyZA==
 labels:     
   app: stable-diffusion  
 name: app-placement-1262-glenrose
 namespace: applications     
spec:
 clusterSelector:    
   matchLabels:      
     cluster.open-cluster-management.io/clusterset: 1262-glenrose
#---
#apiVersion: apps.open-cluster-management.io/v1
#kind: PlacementRule   
#metadata:     
# annotations:
#   open-cluster-management.io/user-group: c3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgsc3lzdGVtOmF1dGhlbnRpY2F0ZWQ=
#   open-cluster-management.io/user-identity: cmljaGFyZA==
# labels:     
#   app: stable-diffusion  
# name: app-placement-staging
# namespace: applications     
#spec:
# clusterSelector:    
#   matchLabels:      
#     cluster.open-cluster-management.io/clusterset: staging
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule   
metadata:     
 annotations:
   open-cluster-management.io/user-group: c3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgsc3lzdGVtOmF1dGhlbnRpY2F0ZWQ=
   open-cluster-management.io/user-identity: cmljaGFyZA==
 labels:     
   app: stable-diffusion  
 name: app-placement-all-stores
 namespace: applications     
spec:
 clusterSelector:    
   matchLabels:      
     clusterType: store