---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/gpu-operator-certified.nvidia-gpu-operator: ""
  name: gpu-operator-certified
  namespace: nvidia-gpu-operator
spec:
  channel: patched-in-overlay
  installPlanApproval: Manual
  name: gpu-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
