kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-cnv

bases:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: kubevirt-hyperconverged
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'