apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: hub-cluster
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: Exists}
