apiVersion: v1
entries:
  compliance:
  - apiVersion: v2
    created: "2023-02-10T10:29:33.244643+11:00"
    dependencies:
    - name: operator
      repository: https://richmitch.github.io/ocp-cluster-management/charts/
      version: 0.2.0
    description: Installs the Red Hat Compliance Operator
    digest: 7e0a1d06b09644a78bbb5b788ec5d650d44af29ea52121db7cf568e4169685c6
    maintainers:
    - name: richmitch
    name: compliance
    type: application
    urls:
    - https://richmitch.github.io/ocp-cluster-management/charts/compliance-0.1.1.tgz
    version: 0.1.1
  gitops:
  - apiVersion: v2
    created: "2023-02-10T10:29:33.246039+11:00"
    dependencies:
    - name: operator
      repository: https://richmitch.github.io/ocp-cluster-management/charts/
      version: 0.2.1
    description: Installs the Red Hat GitOps Operator
    digest: fb92abf8e67e4df09b558affe573d33a9af45c5f2e2279606b5eab05bae055e0
    maintainers:
    - name: richmitch
    name: gitops
    type: application
    urls:
    - https://richmitch.github.io/ocp-cluster-management/charts/gitops-0.1.0.tgz
    version: 0.1.0
  nfd:
  - apiVersion: v2
    created: "2023-02-10T10:29:33.250454+11:00"
    dependencies:
    - name: operator
      repository: https://richmitch.github.io/ocp-cluster-management/charts/
      version: 0..0
    description: Installs the Red Hat NFD Operator
    digest: 4d747e738775aec94dacd12dbd3c354185f36882a4aad5d1e3e7eecd2acbb20f
    maintainers:
    - name: richmitch
    name: nfd
    type: application
    urls:
    - https://richmitch.github.io/ocp-cluster-management/charts/nfd-0.3.0.tgz
    version: 0.3.0
  nmstate:
  - apiVersion: v2
    created: "2023-02-10T10:29:33.252088+11:00"
    dependencies:
    - name: operator
      repository: https://richmitch.github.io/ocp-cluster-management/charts/
      version: 0.2.1
    description: Installs the Kubernetes NMState Operator
    digest: 95d8b383db26435a727efb046b7e8ef7253bf01d41777b0fa82d2201a76570a2
    maintainers:
    - name: richmitch
    name: nmstate
    type: application
    urls:
    - https://richmitch.github.io/ocp-cluster-management/charts/nmstate-0.1.1.tgz
    version: 0.1.1
  operator:
  - apiVersion: v2
    appVersion: latest
    created: "2023-02-10T10:29:33.252482+11:00"
    description: A library Helm chart for OpenShift Operator installation
    digest: d61b392e26714fb1fc9d0c4987f24d895ae0735f458e946faec021f90462b2bb
    home: https://github.com/richmitch/ocp-cluster-management/charts
    maintainers:
    - name: richmitch
    name: operator
    type: library
    urls:
    - https://richmitch.github.io/ocp-cluster-management/charts/operator-0.2.1.tgz
    version: 0.2.1
  operatorhub:
  - apiVersion: v2
    created: "2023-02-10T10:29:33.253414+11:00"
    dependencies:
    - name: operator
      repository: https://richmitch.github.io/ocp-cluster-management/charts/
      version: 0.2.0
    description: Helper application for installing operators from OperatorHub
    digest: 5d503c8ebbd07c03fddfd98b29bce510c1d8e664319102e41b8e81fb0deb5d91
    maintainers:
    - name: richmitch
    name: operatorhub
    type: application
    urls:
    - https://richmitch.github.io/ocp-cluster-management/charts/operatorhub-0.1.0.tgz
    version: 0.1.0
generated: "2023-02-10T10:29:33.243412+11:00"
