apiVersion: v1
entries:
  nfd:
  - apiVersion: v2
    created: "2023-01-06T14:53:48.019351+11:00"
    dependencies:
    - name: operator
      repository: file://../library/operator
      version: 0.0.1
    description: Installs the Red Hat NFD Operator
    digest: 9a4572a3f267dd64929c23e8f051e8f75f005ea0ae337ffe47f8284c28e9f5ce
    maintainers:
    - name: richmitch
    name: nfd
    type: application
    urls:
    - https://github.com/richmitch/ocp-cluster-management/nfd-0.0.1.tgz
    version: 0.0.1
  operator:
  - apiVersion: v2
    appVersion: latest
    created: "2023-01-06T14:53:48.019876+11:00"
    description: A library Helm chart for OpenShift Operator installation
    digest: 077aa2802cc2539de4c6c8e1e518009a31071cd3730063ea0416a6c459d310eb
    home: https://github.com/richmitch/ocp-cluster-management/charts
    maintainers:
    - name: richmitch
    name: operator
    type: library
    urls:
    - https://github.com/richmitch/ocp-cluster-management/operator-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: latest
    created: "2023-01-06T14:53:48.019635+11:00"
    description: A library Helm chart for OpenShift Operator installation
    digest: daf09a9309ce61b36cfe47804ef5a4fdc5b04209088b1265db2fdb8dc813de58
    home: https://github.com/richmitch/ocp-cluster-management/charts
    maintainers:
    - name: richmitch
    name: operator
    type: library
    urls:
    - https://github.com/richmitch/ocp-cluster-management/operator-0.0.1.tgz
    version: 0.0.1
generated: "2023-01-06T14:53:48.018628+11:00"
