operators:
  - name: nfd
    namespace:
      create: true
      name: openshift-nfd
    subscription:
      channel: stable
      approval: Automatic
      operatorName: nfd
      sourceName: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: true
  - name: nfd2
    namespace:
      create: true
      name: openshift-nfd2
    subscription:
      channel: stable
      approval: Automatic
      operatorName: nfd2
      sourceName: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: true
