kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-operators

#commonAnnotations:
#  argocd.argoproj.io/sync-wave: "0"

resources:
  - file-integrity-operator-namespace.yml
  - file-integrity-operator-subscription.yml
  - file-integrity-operator-operatorgroup.yml