kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-operators

bases:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: openshift-pipelines-operator-rh
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'latest'