apiVersion: apps/v1       
kind: Deployment          
metadata:         
  name: dcgmproftester     
spec:        
  progressDeadlineSeconds: 600         
  replicas: patched-in-overlays
  revisionHistoryLimit: 10
  selector:  
    matchLabels:          
      app: loadtest           
  strategy:  
    rollingUpdate:        
      maxSurge: 25%       
      maxUnavailable: 25% 
    type: RollingUpdate   
  template:  
    metadata:     
      labels:
        app: loadtest         
    spec:    
      containers:         
      - args:
        - --no-dcgm-validation         
        - -t 1004         
        - -d 60           
        image: nvidia/samples:dcgmproftester-2.0.10-cuda11.0-ubuntu18.04      
        imagePullPolicy: IfNotPresent  
        name: container   
        resources:        
          limits:         
            nvidia.com/gpu: "1"        
        securityContext:  
          allowPrivilegeEscalation: true            
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File 
      dnsPolicy: ClusterFirst          
      restartPolicy: Always            
      schedulerName: default-scheduler 
      serviceAccount: dcgmproftester            
      serviceAccountName: dcgmproftester        
      terminationGracePeriodSeconds: 30