apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nvidia-gpu-operator

#commonAnnotations:
#  argocd.argoproj.io/sync-wave: "0"

resources:
  - dcgmproftester-app-clusterrolebinding.yml
  - dcgmproftester-app-deployment.yml
  - dcgmproftester-app-serviceaccount.yml
