apiVersion: v2
name: operatorhub
description: Helper application for installing operators from OperatorHub
type: application
version: 0.1.0
maintainers:
  - name: richmitch
dependencies:
- name: operator
  version: 0.2.0
  repository: https://richmitch.github.io/ocp-cluster-management/charts/