kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-compliance

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: compliance-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: '4.7'