apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/refresh: normal
  name: openshift-pipelines-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: gitops-hub
    server: https://kubernetes.default.svc
  project: gitops-hub
  source:
    path: manifests/operators/pipelines/overlays/latest
    repoURL: https://github.com/richmitch/ocp-cluster-management/
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true