operators:
  - name: compliance
    namespace:
      create: true
      name: openshift-compliance
    subscription:
      channel: stable
      approval: Automatic
      operatorName: compliance-operator
      sourceName: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: true

#operands:
#  - name: argocd-instance
#    namespace: openshift-gitops
#@    kind: ArgoCD
