apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: santa-message

#commonAnnotations:
#  argocd.argoproj.io/sync-wave: "0"

resources:
  - santa-message-app-buildconfig.yml
  - santa-message-app-deployment.yml
  - santa-message-app-imagestream.yml
  - santa-message-app-namespace.yml
  - santa-message-app-route.yml
  - santa-message-app-secret.yml
  - santa-message-app-service.yml