operators:
  - name: gitops
    namespace:
      create: true
      name: openshift-operators
    subscription:
      channel: stable
      approval: Automatic
      operatorName: openshift-gitops-operator
      sourceName: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: true

#operands:
#  - name: argocd-instance
#    namespace: openshift-gitops
#@    kind: ArgoCD
